### ISSUE TITLE
Choice of Container & Object Design

### ISSUE THREAD

**Issue by wjsgus95** [green4469/HeadFirstOOAnD#1]
Guitar collection을 저장하는 container가 list보다는 set이 더 적절하지 않을까 생각합니다. Scalability 면에서 더 적합한 자료형인 것 같아요!

또 기타 가게라고는 하지만 extendibility 측면에서 봤을 때 Guitar의 base class를 InventoryItem 같은 이름으로 두어서 Serial number, price 등을 빼서 두면 기타줄이나 토너 등의 아이템도 같이 관리 할 수 있을 것으로 보입니다.

이를 위해서라도 당연히 Inventory class에서 Inventory item간에 equal operation을 해야할 이유는 전혀 없으니 Guitar class 등 Inventory item class 쪽으로 equal operation이 들어가는게 맞는 것 같아요. 그 부분 동의합니다!

**Comment by green4469** [comment]
Set 을 사용하는 것이 낫다는 것 동의합니다. serialNumber 필드가 기타를 고유하게 식별하기 때문에 Set을 써도 되겠네요~

Guitar 를 한단계 추상화시킨 InventoryItem 추상클래스 도입도 좋은 생각인 것 같아요. 말씀하신 serialNumber 나 price 필드는 모든 상품이 공유한다고 볼 수 있고, 의존관계 관점에서도 Inventory 클래스가 구현클래스인 Guitar 에 의존하는 것보다 추상클래스인 InventoryItem 에 의존하는 편이 낫습니다.

두 상품의 동등성(equality)을 비교하는 로직이 InventoryItem 추상클래스에 존재한다면 문제가 발생하겠죠. 기타 가게를 이용하는 손님이 serialNumber 로 검색하지 않고, 기타의 고유한 속성에 해당하는 builder, model 등의 필드로 비교할 것이기 때문이죠. 

equal operation 로직은 Guitar 와 같은 구현클래스에 들어가고, 추상클래스에서 추상메서드로 Inventory 클래스가 사용할 수 있게끔 만들어주면 해결될 것 같습니다. 

말이 길었네요. 코드로 하는게 나을 것 같아요.
``` java
public abstract class InventoryItem {
    // ...
    public abstract boolean equals(InventoryItem target);
}

public class Guitar extends InventoryItem {
    // ...
    @Override
    public boolean equals(InventoryItem target) {
        if (target instanceof Guitar) {
            Guitar targetGuitar = (Guitar) target;
            // equals 로직 ...
        }
        return false;
    }
}
```

Inventory 클래스의 서치 메서드는 아래와 같이 변하겠네요.
``` java
public class Inventory {
    // ...
    public InventoryItem search(InventoryItem searchItem) {
        return items.stream()
            .filter(searchItem::equals)
            .findFirst()
            .orElseThrow(SearchItemNotFoundException::new);
    }
    // ...
}
```

Inventory 클래스가 Guitar 구현클래스에 의존하지 않다보니, 코드가 훨씬 깔끔해졌습니다! 상품의 동등성을 확인하는 책임을 상품 객체에 위임하니 관심사의 분리(Separation of Concerns)도 좋아졌구요.
